# A list of devices you want to take the screenshots from
devices([
"iPhone 6",
"iPhone 6 Plus",
"iPhone 5s",
])

languages([
"ru-RU"
])

# The name of the scheme which contains the UI Tests
scheme "FastLane"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "./FastLane.xcworkspace"
